### PR TITLE
Virtual Account service

### PR DESCRIPTION
**Pull request by stanleynguyen**

### CODE REVIEW

**Comment by hakiemaul** [comment]
hey this looks good, i'm wondering about how we can track our library usage, do you think we can send some specific header that is unique to each library, then we can track in kibana?

**Comment by hakiemaul** [comment]
how should we manage changelog on this?

**Comment by hakiemaul** [comment]
also, let's publish this once this get merged!~~

**Comment by stanleynguyen** [comment]
@hakiemaul Let me have a word with Luminto and gather some info from the API troops

**Comment by stanleynguyen** [comment]
@hakiemaul I was thinking of publishing this as an `alpha` version (indicating not all features are available) and only have change log once we get past `alpha` stage - reason being that we are still implementing main features, there's not much point to change log. Please correct me if I'm wrong but my idea of change log is more for keeping our users in the loop once we have  a certain number of users

**Comment by hakiemaul** [comment]
> @hakiemaul I was thinking of publishing this as an `alpha` version (indicating not all features are available) and only have change log once we get past `alpha` stage - reason being that we are still implementing main features, there's not much point to change log. Please correct me if I'm wrong but my idea of change log is more for keeping our users in the loop once we have a certain number of users

actually this makes sense! since this would be used by non internal user, i think this is a good approach.

i was thinking of changelog for our internal services haha

**Pull request merged**
